### ISSUE TITLE
Conda installing wrong python version of Pandas

### ISSUE THREAD

**Issue by pboueri** [AnacondaRecipes/pandas-feedstock#8]
Hello,

I'm trying to install pandas in a fresh conda environment for python 3.8. Whenever I do however, it installs the python 3.7 build. I had one person reproduce it on a separate machine, and one person was unable to and it installed the correct version. I'm raising this ticket in the hopes that it's either obvious or not an issue. 

Steps to reproduce:
```
conda create -n test python=3.8
conda activate test
conda install pandas
```

which results in:
![image](https://user-images.githubusercontent.com/58823976/126365739-a2f601b7-4fab-40f9-ae94-afe8d980c663.png)

note the py37 build for pandas being installed.

here's my conda install info:

```
active environment : test
    active env location : /Users/pboueri/miniconda3/envs/test
            shell level : 2
       user config file : /Users/pboueri/.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __osx=10.15.4=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/pboueri/miniconda3  (writable)
      conda av data dir : /Users/pboueri/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/pboueri/miniconda3/pkgs
                          /Users/pboueri/.conda/pkgs
       envs directories : /Users/pboueri/miniconda3/envs
                          /Users/pboueri/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.22.0 CPython/3.7.4 Darwin/19.4.0 OSX/10.15.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

Thank you!

**Comment by pboueri** [comment]
Quick update, 

the person on whose machine the install _did_ work had the following in their ~/.condarc

```
channel_priority: strict
channels:
  - conda-forge
  - defaults
```

When i add the same, the correct version installs, which makes me believe it _is_ and issue and is related to this repository. 

Thanks again for all you do!

**Comment by skupr-anaconda** [comment]
The issue was fixed https://github.com/pandas-dev/pandas/issues/42627#issuecomment-883603554

**Comment by pboueri** [comment]
Thanks! I will never unsee the conda hotfix script
